### ISSUE TITLE
bad language tag: "Oliver He"@ualr.edu) 

### ISSUE THREAD

**Issue by leonqli** [OPMI/opmi#3]
`    <owl:Class rdf:about="http://purl.obolibrary.org/obo/OPMI_0000215">
...
       <dc:creator xml:lang="ualr.edu)">Oliver He</dc:creator>
        <rdfs:label xml:lang="en">last four digits of social security number</rdfs:label>
    </owl:Class>
    `

**Comment by yongqunh** [comment]
This is now solved. thanks.
